import os
import pandas as pd
import psycopg2
import logging
import mimetypes
import shutil
import zipfile
from pathlib import Path
import re

# Setup logger
logger = logging.getLogger(__name__)

def get_db_conn(db_config):
    return psycopg2.connect(**db_config)

def safe_float_convert(value, default=0.0):
    """
    Industry-grade float converter.
    Aggressively strips 'INR', 'Rs', ',', spaces, 'kg', and other junk.
    """
    try:
        if value is None or pd.isna(value):
            return default

        str_value = str(value).strip()
        # Filter out common non-numeric placeholders
        if not str_value or str_value.lower() in ['', 'n/a', 'na', 'null', 'nan', 'tbd', '-', 'nil']:
            return default

        # Regex: Keep ONLY digits, decimal points, and minus signs
        clean_value = re.sub(r'[^\d.-]', '', str_value)
        
        if not clean_value or clean_value in {'.', '-'}:
            return default

        return float(clean_value)
    except Exception as e:
        logger.warning(f"Value conversion failed for '{value}': {e}")
        return default

def process_knowledge_base_upload(excel_path, zip_path, db_config):
    """
    Process the uploaded Excel and Zip file to repopulate the 'ideas' table.
    """
    temp_extract_dir = Path("temp_extract_images")
    conn = None
    cursor = None
    
    try:
        # 1. Clean and Re-create Temp Directory
        if temp_extract_dir.exists():
            shutil.rmtree(temp_extract_dir)
        temp_extract_dir.mkdir(parents=True, exist_ok=True)

        # 2. Extract Zip
        logger.info("Extracting images zip...")
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(temp_extract_dir)

        # 3. Locate specific image folders recursively
        # Users might zip the parent folder or just the subfolders, so we search.
        image_map = {'proposal': None, 'mg': None, 'competitor': None}
        
        for root, dirs, files in os.walk(temp_extract_dir):
            lower_dirs = [d.lower() for d in dirs]
            # Check for target directories
            if 'proposal' in lower_dirs:
                image_map['proposal'] = Path(root) / dirs[lower_dirs.index('proposal')]
            if 'mg' in lower_dirs:
                image_map['mg'] = Path(root) / dirs[lower_dirs.index('mg')]
            if 'competitor' in lower_dirs:
                image_map['competitor'] = Path(root) / dirs[lower_dirs.index('competitor')]

        # 4. Load Excel
        logger.info(f"Reading Excel: {excel_path}")
        df_ideas = pd.read_excel(excel_path, sheet_name='AIML Dummy ideas') # Ensure sheet name matches user template
        
        # Column Mapping (Same as original script)
        column_mapping = {
            'Idea Id': 'idea_id', 'Cost Reduction Idea Proposal': 'cost_reduction_idea',
            'Reason of cost reduction proposal': 'reason', 'MGI Estimated Gross saving': 'mgi_gross_saving',
            'Estimated Cost Savings - Breakup': 'estimated_cost_savings', 'Saving Value(INR)': 'saving_value_inr',
            'Weight Saving(Kg)': 'weight_saving', 'Group ID': 'group_id',
            'Status (OK/TBD/NG)': 'status', 'Way Forward': 'way_forward', 'Dept': 'dept',
            'Target Date': 'target_date', 'KD/LC': 'kd_lc', 'Wtd. Avg.': 'wtd_avg',
            'Est. Impl. Date': 'est_impl_date', 'Investment (Cr)': 'investment_cr', 'CAPEX': 'capex',
            'MGI carline': 'mgi_carline', 'Banchmarking carline': 'benchmarking_carline',
            'MG Product Scenario': 'mg_product_scenario', 'Competitor Product Scenario': 'competitor_product_scenario',
            'Purpose on MG product': 'purpose_mg_product', 'Purpose on Competitor Product': 'purpose_competitor_product',
            'Impact on Other Systems': 'impact_other_systems', 'Client Proposal/Rejection Statement': 'client_statement',
            'CAE Required (No/Yes)': 'cae_required', 'Homologation Required (No/Yes)': 'homologation_required',
            'Styling Change (No/Yes)': 'styling_change', 'Part Level Testing (No/Yes)': 'part_level_testing',
            'Assembly Trials (No/Yes)': 'assembly_trials', 'CAD Drawing Update (No/Yes)': 'cad_drawing_update',
            'ECN Required (No/Yes)': 'ecn_required', 'Part Production Trials (No/Yes)': 'part_production_trials',
            'Vehicle Level Testing (No/Yes)': 'vehicle_level_testing', 'Idea Generated By': 'idea_generated_by',
            'New Tool Required (No/Yes)': 'new_tool_required', 'New Tool Cost': 'new_tool_cost',
            'Tool Modification Required (No/Yes)': 'tool_modification_required', 'Tool Modification Cost': 'tool_modification_cost',
            'Variants': 'variants', 'Current Status': 'current_status', 'Resp': 'resp',
            'Mix': 'mix', 'Volume': 'volume', 'Purchase Praposal': 'purchase_proposal',
            'Interest': 'interest', 'Payback months': 'payback_months',
            'MGI PE Feasibilty': 'mgi_pe_feasibility', 'Homeroom Approval': 'homeroom_approval',
            'PP Approval': 'pp_approval', 'Supplier feasibility': 'supplier_feasibility',
            'Financial Feasibility': 'financial_feasibility', 'Proposal Image': 'proposal_image_filename',
            'MG Vehicle Image': 'mg_vehicle_image', 'Competitor Vehicle Image': 'competitor_vehicle_image'
        }
        df_ideas.rename(columns=column_mapping, inplace=True)
        df_ideas = df_ideas[df_ideas['cost_reduction_idea'].notnull()].reset_index(drop=True)

        # 5. Database Operations
        conn = get_db_conn(db_config)
        cursor = conn.cursor()

        # Re-create Ideas Table (Preserve Chat History by NOT dropping it)
        cursor.execute("DROP TABLE IF EXISTS ideas;") 
        
        # Copy-paste the Create Table SQL from your original script, 
        # ensuring it includes the BYTEA columns
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS ideas (
            id SERIAL PRIMARY KEY,
            idea_id TEXT UNIQUE,
            cost_reduction_idea TEXT, reason TEXT, mgi_gross_saving REAL,
            estimated_cost_savings TEXT, saving_value_inr REAL, weight_saving REAL,
            group_id TEXT, status TEXT, way_forward TEXT, dept TEXT, target_date TEXT,
            kd_lc TEXT, wtd_avg REAL, est_impl_date TEXT, investment_cr REAL, capex REAL,
            mgi_carline TEXT, benchmarking_carline TEXT, mg_product_scenario TEXT,
            competitor_product_scenario TEXT, purpose_mg_product TEXT, purpose_competitor_product TEXT,
            impact_other_systems TEXT, client_statement TEXT, cae_required TEXT,
            homologation_required TEXT, styling_change TEXT, part_level_testing TEXT,
            assembly_trials TEXT, cad_drawing_update TEXT, ecn_required TEXT,
            part_production_trials TEXT, vehicle_level_testing TEXT, idea_generated_by TEXT,
            new_tool_required TEXT, new_tool_cost REAL, tool_modification_required TEXT,
            tool_modification_cost REAL, variants TEXT, current_status TEXT, resp TEXT,
            mix TEXT, volume TEXT, purchase_proposal TEXT, interest TEXT,
            payback_months TEXT, mgi_pe_feasibility TEXT, homeroom_approval TEXT,
            pp_approval TEXT, supplier_feasibility TEXT, financial_feasibility TEXT,
            proposal_image_filename TEXT, mg_vehicle_image TEXT, competitor_vehicle_image TEXT,
            user_input TEXT, response_text TEXT, image_path TEXT,
            proposal_image_data BYTEA, proposal_image_mimetype TEXT,
            mg_vehicle_data BYTEA, mg_vehicle_mimetype TEXT,
            competitor_vehicle_data BYTEA, competitor_vehicle_mimetype TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """
        cursor.execute(create_table_sql)
        
        # 6. Insert Data
        inserted_count = 0
        for _, row in df_ideas.iterrows():
            # Prepare Images
            img_data = {}
            for itype in ['proposal', 'mg', 'competitor']:
                img_data[f'{itype}_blob'] = None
                img_data[f'{itype}_mime'] = None
                
                # Get filename from Excel
                fname_col = 'proposal_image_filename' if itype == 'proposal' else f'{itype}_vehicle_image'
                fname = row.get(fname_col)

                # If folder exists and filename exists
                if image_map[itype] and fname and not pd.isna(fname) and str(fname).lower() != 'nan':
                    fpath = image_map[itype] / str(fname)
                    if fpath.exists():
                        with open(fpath, 'rb') as f:
                            img_data[f'{itype}_blob'] = f.read()
                        img_data[f'{itype}_mime'] = mimetypes.guess_type(fpath)[0] or 'application/octet-stream'

            # Insert Query
            cursor.execute("""
                INSERT INTO ideas (
                    idea_id, cost_reduction_idea, reason, mgi_gross_saving,
                    estimated_cost_savings, saving_value_inr, weight_saving,
                    group_id, status, way_forward, dept, target_date, kd_lc,
                    wtd_avg, est_impl_date, investment_cr, mgi_carline,
                    benchmarking_carline, mg_product_scenario, competitor_product_scenario,
                    purpose_mg_product, purpose_competitor_product, impact_other_systems,
                    client_statement, cae_required, homologation_required, styling_change,
                    part_level_testing, assembly_trials, cad_drawing_update, ecn_required,
                    part_production_trials, vehicle_level_testing, idea_generated_by,
                    new_tool_required, new_tool_cost, tool_modification_required,
                    tool_modification_cost, variants, current_status, resp, mix,
                    volume, purchase_proposal, interest, payback_months, mgi_pe_feasibility,
                    homeroom_approval, pp_approval, supplier_feasibility, financial_feasibility,
                    proposal_image_filename, mg_vehicle_image, competitor_vehicle_image,
                    proposal_image_data, proposal_image_mimetype,
                    mg_vehicle_data, mg_vehicle_mimetype,
                    competitor_vehicle_data, competitor_vehicle_mimetype
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
            """, (
                str(row.get('idea_id', 'N/A')), str(row.get('cost_reduction_idea', 'N/A')),
                str(row.get('reason', 'N/A')), safe_float_convert(row.get('mgi_gross_saving')),
                str(row.get('estimated_cost_savings', 'N/A')), safe_float_convert(row.get('saving_value_inr')),
                safe_float_convert(row.get('weight_saving')), str(row.get('group_id', 'N/A')),
                str(row.get('status', 'N/A')), str(row.get('way_forward', 'N/A')),
                str(row.get('dept', 'N/A')), str(row.get('target_date', 'N/A')),
                str(row.get('kd_lc', 'N/A')), safe_float_convert(row.get('wtd_avg')),
                str(row.get('est_impl_date', 'N/A')), safe_float_convert(row.get('investment_cr')),
                str(row.get('mgi_carline', 'N/A')), str(row.get('benchmarking_carline', 'N/A')),
                str(row.get('mg_product_scenario', 'N/A')), str(row.get('competitor_product_scenario', 'N/A')),
                str(row.get('purpose_mg_product', 'N/A')), str(row.get('purpose_competitor_product', 'N/A')),
                str(row.get('impact_other_systems', 'N/A')), str(row.get('client_statement', 'N/A')),
                str(row.get('cae_required', 'N/A')), str(row.get('homologation_required', 'N/A')),
                str(row.get('styling_change', 'N/A')), str(row.get('part_level_testing', 'N/A')),
                str(row.get('assembly_trials', 'N/A')), str(row.get('cad_drawing_update', 'N/A')),
                str(row.get('ecn_required', 'N/A')), str(row.get('part_production_trials', 'N/A')),
                str(row.get('vehicle_level_testing', 'N/A')), str(row.get('idea_generated_by', 'N/A')),
                str(row.get('new_tool_required', 'N/A')), safe_float_convert(row.get('new_tool_cost')),
                str(row.get('tool_modification_required', 'N/A')), safe_float_convert(row.get('tool_modification_cost')),
                str(row.get('variants', 'N/A')), str(row.get('current_status', 'N/A')),
                str(row.get('resp', 'N/A')), str(row.get('mix', 'N/A')),
                str(row.get('volume', 'N/A')), str(row.get('purchase_proposal', 'N/A')),
                str(row.get('interest', 'N/A')), str(row.get('payback_months', 'N/A')),
                str(row.get('mgi_pe_feasibility', 'N/A')), str(row.get('homeroom_approval', 'N/A')),
                str(row.get('pp_approval', 'N/A')), str(row.get('supplier_feasibility', 'N/A')),
                str(row.get('financial_feasibility', 'N/A')), row.get('proposal_image_filename'),
                row.get('mg_vehicle_image'), row.get('competitor_vehicle_image'),
                img_data['proposal_blob'], img_data['proposal_mime'],
                img_data['mg_blob'], img_data['mg_mime'],
                img_data['competitor_blob'], img_data['competitor_mime']
            ))
            inserted_count += 1
        
        conn.commit()
        return True, f"Successfully inserted {inserted_count} records."

    except Exception as e:
        if conn: conn.rollback()
        logger.error(f"Upload Process Error: {e}")
        return False, str(e)
    finally:
        if cursor: cursor.close()
        if conn: conn.close()
        # Cleanup Temp
        if temp_extract_dir.exists():
            shutil.rmtree(temp_extract_dir)